export const makeupFitler = {
	Blush: {
		category: ['Powder', 'Cream'],
		tag: [
			'Vegan',
			'Gluten free',
			'Canadian',
			'Natural',
			'Non-gmon',
			'Purpicks',
			'Usda organic',
			'Organic',
			'Certclean',
			'Ewg verified',
			'Hypoallergenic',
			'No talc',
		],
	},
	Bronzer: {
		category: ['Powder'],
		tag: [
			'Gluten free',
			'Canadian',
			'Natural',
			'Organic',
			'Vegan',
			'Purpicks',
			'Ewg verified',
		],
	},
	Eyebrow: {
		category: ['Pencil'],
		tag: ['Ewg verified', 'Purpicks'],
	},
	Eyeliner: {
		category: ['Liquid', 'Pencil', 'Gel', 'Cream'],
		tag: [
			'Vegan',
			'Natural',
			'Canadian',
			'Gluten free',
			'Organic',
			'Purpicks',
			'Certclean',
			'Ewg verified',
			'Hypoallergenic',
			'No talc',
			'Ecocert',
		],
	},
	// tener en cuenta que este tipo de producto hay productos que no tienen categoria
	Eyeshadow: {
		category: ['Palette', 'Pencil', 'Cream', 'Without category'],
		tag: [
			'Vegan',
			'Canadian',
			'Natural',
			'Non-gmon',
			'Purpicks',
			'Certclean',
			'Ewg verified',
			'Organic',
			'Usda organic',
			'Hypoallergenic',
			'No talc',
			'Ecocert',
		],
	},
	Foundation: {
		category: [
			'Concealer',
			'Liquid',
			'Contour',
			'Bb cc',
			'Cream',
			'Mineral',
			'Powder',
			'Highlighter',
		],
		tag: [
			'Vegan',
			'Canadian',
			'Natural',
			'Gluten free',
			'Purpicks',
			'Certclean',
			'Ewg verified',
			'Hypoallergenic',
			'No talc',
			'Water free',
			'Cruelty free',
			'Alcohol free',
			'Oil free',
			'Silicone free',
		],
	},
	// el nombre del tipo de producto va separado "Lip liner"
	'Lip liner': {
		category: ['Pencil'],
		tag: [
			'Natural',
			'Vegan',
			'Glutten free',
			'Canadian',
			'Purpicks',
			'Ewg verified',
			'Hypoallergenic',
			'No talc',
			'Cruelty free',
		],
	},
	Lipstick: {
		category: ['Lipstick', 'Lip gloss', 'Liquid', 'Lip stain'],
		tag: [
			'Canadian',
			'Natural',
			'Gluten free',
			'Non-gmo',
			'Peanut free product',
			'Vegan',
			'Cruelty free',
			'Organic',
			'Purpicks',
			'Certclean',
			'Chemical free',
			'Ewg verified',
			'Hypoallergenic',
			'No talc',
		],
	},
	// este tipo de producto no tiene categoria
	Mascara: {
		category: ['Without category'],
		tag: [
			'Natural',
			'Gluten free',
			'Vegan',
			'Canadian',
			'Organic',
			'Purpicks',
			'Ewg verified ',
			'Hypoallergenic',
			'No talc',
			'Ecocert',
			'Usda organic',
			'Certclean',
		],
	},
	// este tipo de producto no tiene categoria
	// el nombre del tipo de producto va separado "Nail polish"
	'Nail polish': {
		category: ['Without category'],
		tag: [
			'Vegan',
			'Canadian',
			'Natural',
			'Gluten free',
			'Fair trade',
			'Sugar free ',
			'Non-gmo',
			'Dairy free',
		],
	},
};
